name: Deploy feature branches to nonprod buckets

on: 
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: nonproduction-aj
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
      - name: set up node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci 
          npm run build
      - name: Deploy file to buckets
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive
